# Generated by Django 4.0.5 on 2022-06-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='defaultAvatar.png', null=True, upload_to='profile_images'),
        ),
    ]
